### ISSUE TITLE
Add `setFramework:` call

### ISSUE THREAD

**Issue by ekilah** [react-native-contrib/react-native-heyzap#8]
This will report to Heyzap that the react native wrapper is being used. This doesn't matter much, but could help in the future with debugging issues with the wrapper.

You can add this to the wrapper: `[HeyzapAds setFramework:@"react"]` before calling the start method, or you can use this alternative start method for convenience: `+ (void) startWithPublisherID:(NSString *)publisherID andOptions:(HZAdOptions)options andFramework: (NSString *) framework;`

Android has similar methods. Just use the same string in both places ("react") 👍

**Comment by hassankhan** [comment]
Would it be better to use `react-native` instead?

**Comment by ekilah** [comment]
That's fine / more accurate, yep.
